config/routes.rb
Rails.application.routes.draw do

  root 'authentication#sign_in'

  get 'sign_in' => 'authentication#sign_in'
  post 'sign_in' => 'authentication#login'
  get 'log_out' => 'authentication#log_out' 
  get 'new_user' => 'authentication#new_user'
  put 'new_user' => 'authentication#register'

  put 'photos/trash' => 'photos#trash'
  post 'photos/upload' => 'photos#upload'

  resources :photos do 
    resources :comments
  end

  resources :albums

  get 'search' => 'search#search'

  get 'user' => 'user#home'
  get 'user/:id' => 'user#user'

end

app/models/album.rb
class Album
  include Mongoid::Document
  field :name

  validates_presence_of :name

  belongs_to :user
  has_and_belongs_to_many :photos

  index({ name: 1 }, { unique: true })
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :name
  field :content
  embedded_in :photo, inverse_of: :comments
end

app/models/photo.rb
class Photo
	include Mongoid::Document
	include Mongoid::Paperclip
	field :name
	field :category
	validates_presence_of :name
	validates_presence_of :category	

	belongs_to :user
	embeds_many :comments
	has_and_belongs_to_many :albums

	index({ name: 1 }, { unique: true })

	#for photo uploads
	has_mongoid_attached_file :image,
		styles: { thumb: "180x180>" }
	validates_attachment :image, 
		presence: true,
		content_type: { content_type: "image/jpeg" }
end

app/models/user.rb
class User
  include Mongoid::Document
  field :username
  field :password
  field :password_confirmation

  validates_presence_of :username, :password
  validates_uniqueness_of :username
  validates_confirmation_of :password
  has_many :photos
  has_many :albums

  def self.authenticate(username, password)
  	user = User.find_by(username: username)
  	if user && password == user.password
  		user
  	else
  		nil
  	end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user_id = session[:user_id]

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    @photo = Photo.find(params[:album][:photos])
    @album.photos.push(@photo)
    
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
	def sign_in
		@user = User.new
	end

	def login
		username = params[:user][:username]
		password = params[:user][:password]
		@user = User.authenticate(username,password)

		if @user
			session[:user_id] = @user.id.to_s
			redirect_to photos_path
		else  
			render action: "sign_in"
		end
	end

	def new_user 
		@user = User.new
	end

	def register
		# if User.find_by(username: params[:user][:username]).nil?
			@user = User.new(user_params)

			if @user.valid?
				@user.save
				session[:user_id] = @user.id.to_s
				redirect_to photos_path
			else 
				render action: "new_user"
			end
	end

	def log_out
		session[:user_id] = nil
	end

	private

  def user_params
  	params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	  @photo = Photo.find(params[:photo_id])
	  @comment = @photo.comments.create!(params[:comment].permit!)
	  redirect_to @photo, notice: "Comment created!"
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    if !params[:category].nil?
      @photos = Photo.where(category: params[:category])
    else
      @photos = Photo.all
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = session[:user_id]

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /photos/upload
  def upload
    @photo = Photo.new({
      'name' =>params[:file].original_filename,
      'image'=>params[:file],
      'category'=>'none'
    })
    @photo.user_id = session[:user_id]

    if @photo.save
      head :created, location: @photo
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def trash
    @trashbin = Photo.find(params[:photo_ids])
    destroyed_photos = []
    @trashbin.each do |trash|
      if trash.user_id.eql?(current_user)
        if trash.destroy
          #TODO: display destroyed_photos via ajax
          destroyed_photos.push trash.id
        end
      end
    end

    respond_to do |format|
      format.js { render nothing: true }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name,:category,:image)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		if !params[:search][:query].blank?
			@search_query = params[:search][:query]
			@photos = Photo.text_search(@search_query)
			@albums = Album.text_search(@search_query)
		end
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def home
		@photos = current_user.photos
		@albums = current_user.albums 
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
	CATEGORIES_ENUM = [ 
		'animal',
		'cityscape',
		'fashion',
		'landscape',
		'people',
		'plant',
		'portrait',
		'homepage'
	]
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <% if @album.photos.size > 0 %>
    <h2>Photos</h2>
    <div class="container-fluid">
      <% @album.photos.each do |photo| %>
        <div class="col-xs-6 col-sm-3 col-md-2">
          <%= render partial: 'shared/thumbnail', locals: {photo: photo} %>
        </div>
      <% end %>
    </div>
  <% end %>
  <h2>Add photo</h2>
  <div class="field form-group">
    <%= f.label :photos %><br/>
    <%= f.collection_select :photos, Photo.all, :id, :name %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/albums/_sidebar_left.html.erb
<ul class="nav nav-sidebar">
	<li><h3>Albums</h3></li>
	<li><%= link_to "Recently Added", albums_path%></li>
	<li><%= link_to "Favorites", albums_path%></li>
	<li><%= link_to "All", albums_path %></li>
	<li><%= link_to "Mine", albums_path%></li>
</ul>
<ul class="nav nav-sidebar">
	<li><%= link_to(new_photo_path) do %>
    <span class="glyphicon glyphicon-cloud-upload"></span> Upload
  <% end %>
  </li>
</ul>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<table class="table table-striped table-hover">
  <% @albums.each do |album| %>
    <tr class="album-frame">
      <td>
        <div class="thumbnail">
          <div id=<%= "album_carousel_"+album.id.to_s %> class="carousel slide" data-ride="carousel" data-interval="false">
            <div class="carousel-inner" role="listbox">
              <% album.photos.each do |photo| %>
                <div class="item">
                  <%= link_to(album) do %>
                    <%= image_tag photo.image.url(:thumb), class: "img-thumbnail" %>
                  <% end %>
                </div>
              <% end %>
            </div>

            <a class="left carousel-control" href=<%= "#album_carousel_"+album.id.to_s %> role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" style="font-size:15px" aria-hidden="true"></span>
            </a>
            <a class="right carousel-control" href=<%= "#album_carousel_"+album.id.to_s %> role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" style="font-size:15px" aria-hidden="true"></span>
            </a>
          </div>
        </div>
      </td>
      <td>
        <div class="caption">
          <%= album.name %>
          <p class="owner"><%= album.user.username if !album.user.nil? %></p>
          <% if album.user == current_user %>
            <%= link_to 'Edit', edit_album_path(album) %>
            <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<% if @album.photos.size > 0 %>
	<h2>Photos</h2>
	<div class="container-fluid">
	<% @album.photos.each do |photo| %>
	  <div class="col-xs-6 col-sm-3 col-md-2">
	    <%= render partial: 'shared/thumbnail', locals: {photo: photo} %>
	  </div>
	<% end %>
	</div>
<% end %>

<% if @album.user == current_user %>         
  <%= link_to 'Edit', edit_album_path(@album) %>
<% end %>

app/views/authentication/log_out.html.erb
<h1>You have logged off!</h1>

app/views/authentication/new_user.html.erb
<h1>Sign Up</h1>

<%= form_for @user, as: :user, url: new_user_path, method: :put do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <% @user.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
	<div class="field form-group">
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </div>
  <div class="field form-group">
    <%= f.label :password %><br/>
    <%= f.text_field :password %>
  </div>
  <div class="field form-group">
    <%= f.label :password_confirmation %><br/>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/authentication/sign_in.html.erb
<div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-4 col-xs-offset-4"> 
	<div class="panel panel-default sign-in">
		<%= form_for :user, url: sign_in_path do |f| %>
			<%= f.text_field :username, value: "", placeholder: "Username" %>
			<%= f.text_field :password, value: "", placeholder: "Password" %>
			<%= f.submit "Login", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

<div class="carousel slide carousel-fade" id="carousel-sign-in" data-interval="10000" data-pause="none" data-ride="carousel">
	<ol class="carousel-indicators">
		<li data-target="#carousel-sign-in" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-sign-in" data-slide-to="1"></li>
		<li data-target="#carousel-sign-in" data-slide-to="2"></li>
	</ol>

	<div class="carousel-inner" id="homepage-carousel" role="listbox">
		<div class="item active">
			<%= image_tag 'signinslidedefault0.jpeg' %> 
			<div class="carousel-caption">
				<h3><button type="button" class="btn btn-lg btn-primary scrollTop">Get started</button></h3>
			</div>
		</div>
		<div class="item">
			<%= image_tag 'signinslidedefault1.jpeg' %> 
			<div class="carousel-caption">
				<h3><button type="button" class="btn btn-lg btn-primary scrollTop">Get started</button></h3>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <style><%= yield :stylesheets %></style>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render '/shared/navbar' %>
</head>
<body>
<!-- 	<% if current_user %>
		<div class="col-sm-2 col-md-2 sidebar sidebar-left">
			<%= render "shared/sidebar_left" %>
		</div>
	<% end %> -->
	<%= yield %>
<!-- 	<div class="col-md-2" role="complementary">
		<%= render "shared/sidenav_right" %>
	</div> -->
</body>
</html>

app/views/layouts/sign_in.html.erb
<% content_for :stylesheets do %>
	.navbar {display:none}
<% end %>

<!-- <%= render template: "layouts/application" %> -->

app/views/photos/_sidebar_left.html.erb
<ul class="nav nav-sidebar">
	<li><h3>Photos
		<button type="button" class="btn btn-primary" id="quick-upload">
			<span class="glyphicon glyphicon-plus"></span>
		</button></h3></li>
	<li><%= link_to "Favorites", photos_path%></li>
	<li>
		<div class="panel-group" id="category-accordion" role="tablist" aria-multiselectable="true">
			<div class="panel panel-default">
				<div class="panel-heading" id ="category-heading" role="tab"> 
					<a class="collapsed" data-toggle="collapse" data-parent="#category-accordion" href="#category-collapse" role="button" aria-expanded="true" aria-controls="category-collapse">Category 
						<span class="caret"></span>
					</a>
				</div>
				<div class="panel-collapse collapse" id="category-collapse" role="tabpanel" aria-labelledby="category-heading">
					<ul class="list-group">
						<li class="list-group-item">
							<%= link_to "Animal", photos_path(category: 'animal') %>
						</li>
						<li class="list-group-item">
							<%= link_to "Fashion", photos_path(category: 'fashion') %>
						</li>
						<li class="list-group-item">
							<%= link_to "Landscape", photos_path(category: 'landscape') %>
						</li>
						<li class="list-group-item">
							<%= link_to "People", photos_path(category: 'people') %>
						</li>
						<li class="list-group-item">
							<%= link_to "Plant", photos_path(category: 'plant') %>
						</li>
						<li class="list-group-item">
							<%= link_to "Portrait", photos_path(category: 'portrait') %>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</li>
	<li><%= link_to "All", photos_path %></li>
	<li><%= link_to "Mine", photos_path%></li>
</ul>
<ul class="nav nav-sidebar">
	<li><%= link_to(new_photo_path) do %>
    <span class="glyphicon glyphicon-cloud-upload"></span> New Photo
  <% end %>
  </li>
  <li>
  <a class="btn btn-primary" data-toggle="collapse" href="#trash" aria-expanded="false" aria-controls="trash">Trash Bin</a>
  <div class="collapse" id="trash">
  	<button type="button" class="btn btn-primary" id="restore">
			<span class="glyphicon glyphicon-share-alt"></span>
		</button>
		<button type="button" class="btn btn-primary" id="delete">
			<span class="glyphicon glyphicon-trash"></span>
		</button>
  	<div class="well" id="trashbin">
	  	1.Drag and drop photos here to add them to trash 2.Empty the trash using the trash can icon or restore them with the restore all icon
		</div>
	</div></li>
</ul>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>
<p>
  <strong>Category:</strong>
  <%= @photo.category %>
</p>

<p>
  <%= image_tag @photo.image.url %>
</p>

<% if @photo.comments.size > 0 %>
  <strong>Comments</strong>
  <% for comment in @photo.comments %>
    <h3><%= comment.name %></h3>
    <p><%= comment.content %></p>
  <% end %>
<% end %>

<strong>New Comment</strong>
<%= form_for [@photo, Comment.new] do |f| %>
  <p><%= f.label :name %> <%= f.text_field :name %></p>
  <p><%= f.text_area :content, :rows => 10 %></p>
  <p><%= f.submit %></p>
<% end %>

<% if @photo.user == current_user %>         
  <%= link_to 'Edit', edit_photo_path(@photo) %>
<% end %>

app/views/search/search.html.erb
<div class="container-fluid">
  <% if !@photos.nil? %>
    <h1> Photos </h1>
    <% @photos.each do |photo| %>
      <div class="col-xs-6 col-sm-3 col-md-2">
        <%= render partial: 'shared/thumbnail', locals: {photo: photo} %>
      </div>
    <% end %>

    <div class="col-xs-6 col-sm-3 col-md-2">
      <div class="thumbnail">
        <div class="caption">
          <%= link_to(new_photo_path) do %>
            <span class="glyphicon glyphicon-upload"></span> Upload New Picture
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
  <% end %>
</div>

<div class="container-fluid">
  <% if !@albums.nil? %> 
    <h1> Albums </h1>
    <% @albums.each do |album| %>
      <div class="col-xs-6 col-sm-3 col-md-2">
        <div class="thumbnail">
          <div id=<%= "album_carousel_"+album.id.to_s %> class="carousel slide" data-ride="carousel" data-interval="false">
            <div class="carousel-inner" role="listbox">
              <% album.photos.each do |photo| %>
                <div class="item">
                  <%= link_to(album) do %>
                    <%= image_tag photo.image.url(:thumb), class: "img-thumbnail" %>
                  <% end %>
                </div>
              <% end %>
            </div>

            <a class="left carousel-control" href=<%= "#album_carousel_"+album.id.to_s %> role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" style="font-size:15px" aria-hidden="true"></span>
            </a>
            <a class="right carousel-control" href=<%= "#album_carousel_"+album.id.to_s %> role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" style="font-size:15px" aria-hidden="true"></span>
            </a>
          </div>
          <div class="caption">
            <h3><%= album.name %></h3>
            <p><%= album.user.username if !album.user.nil? %></p>
            <%= link_to 'Show', album %>
            <% if album.user == current_user %>
              <%= link_to 'Edit', edit_album_path(album) %>
              <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<div class="navbar-brand">
				PhotoApp
			</div>

			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="glyphicon glyphicon-list"></span>
			</button>
		</div>

		<div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to(photos_path) do %>
						<span class="glyphicon glyphicon-camera"></span> Photos
					<% end %>
				</li>
				<li>
					<%= link_to(albums_path) do %>
						<span class="glyphicon glyphicon-th"></span> Albums
					<% end %>
				</li>
			</ul>
			<%= form_for :search, url: search_path, method: :get, html: { class: "navbar-form navbar-left", role: "search"} do |f| %>
				<div class="form-group">
					<%= f.text_field :query, class: "form-control", placeholder: "Search", value: @search_query %>
					<button type="submit" class="btn btn-default">
						<span class="glyphicon glyphicon-search"></span>
					</button>
				</div>
			<% end %>
			<ul class="nav navbar-nav navbar-right">
				<% if current_user %>
					<li>
						<%= link_to(user_path) do %>
							<span class="glyphicon glyphicon-user"></span> <%= current_user.username %>
						<% end %>
					</li>
					<li><%= link_to "Sign Out", log_out_path %></li>
				<% else %>
					<li class="dropdown">
						<%= link_to('#', class: "dropdown-toggle", data: { toggle: "dropdown"}) do %>
							Login
						<% end %>
						<ul class="dropdown-menu">
							<li>
								<%= form_for :user, url: sign_in_path do |f| %>
									<%= f.text_field :username, value: "", placeholder: "Username" %>
									<%= f.text_field :password, value: "", placeholder: "Password" %>
									<%= f.submit "Login", class: "btn btn-primary" %>
								<% end %>
							</li>
						</ul>
					</li>
					<li><%= link_to "Register", new_user_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/shared/_sidebar_left.html.erb
<% if !@photos.nil? %>
	<%= render "photos/sidebar_left" %>
<% elsif !@albums.nil? %>
	<%= render "albums/sidebar_left" %>
<% end %>

app/views/shared/_sidenav_right.html.erb
<nav class="hidden-xs affix">
	<% if !@photos.nil? %>
		<%= render "photos/sidebar_left" %>
	<% elsif !@albums.nil? %>
		<%= render "albums/sidebar_left" %>
	<% end %>
</nav>

app/views/user/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/user/home.html.erb
<div class="container-fluid">
  <% if !@photos.nil? %>
    <h1> My Photos </h1>
    <% @photos.each do |photo| %>
      <div class="col-xs-6 col-sm-3 col-md-2">
        <%= render partial: 'shared/thumbnail', locals: {photo: photo} %>
      </div>
    <% end %>

    <div class="col-xs-6 col-sm-3 col-md-2">
      <div class="thumbnail">
        <div class="caption">
          <%= link_to(new_photo_path) do %>
            <span class="glyphicon glyphicon-upload"></span> Upload New Picture
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
  <% end %>
</div>

<div class="container-fluid">
  <% if !@albums.nil? %> 
    <h1> My Albums </h1>
    <% @albums.each do |album| %>
      <div class="col-xs-6 col-sm-3 col-md-2">
        <div class="thumbnail">
          <div id=<%= "album_carousel_"+album.id.to_s %> class="carousel slide" data-ride="carousel" data-interval="false">
            <div class="carousel-inner" role="listbox">
              <% album.photos.each do |photo| %>
                <div class="item">
                  <%= link_to(album) do %>
                    <%= image_tag photo.image.url(:thumb), class: "img-thumbnail" %>
                  <% end %>
                </div>
              <% end %>
            </div>

            <a class="left carousel-control" href=<%= "#album_carousel_"+album.id.to_s %> role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" style="font-size:15px" aria-hidden="true"></span>
            </a>
            <a class="right carousel-control" href=<%= "#album_carousel_"+album.id.to_s %> role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" style="font-size:15px" aria-hidden="true"></span>
            </a>
          </div>
          <div class="caption">
            <h3><%= album.name %></h3>
            <p><%= album.user.username if !album.user.nil? %></p>
            <%= link_to 'Show', album %>
            <% if album.user == current_user %>
              <%= link_to 'Edit', edit_album_path(album) %>
              <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/user/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/user/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>